server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: classroom-monitoring-backend
  mvc:
    problemdetails:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info
